### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBhNGYzN2ZlNzJkNjdiNWE2ZThjNWQiLCJpYXQiOjE2MjgwNjU1OTEsImV4cCI6MTYyODQyNTU5MX0.Mi4lxpnhb7Q78ybkFXOlrxtHy9kifarbaHmVR8WM53o
@login = { "email": "hello@email.com", "password": "password" }

### Get authenticated user given the token
GET  http://localhost:5000/api/auth
x-auth-token: {{token}}

### Login user and get token
POST  http://localhost:5000/api/auth
content-type: application/json

{{login}}