### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTBhNGYzN2ZlNzJkNjdiNWE2ZThjNWQiLCJpYXQiOjE2MjgwNjU1OTEsImV4cCI6MTYyODQyNTU5MX0.Mi4lxpnhb7Q78ybkFXOlrxtHy9kifarbaHmVR8WM53o
@profile = { "firstName": "John", "lastName": "Doe", "username": "john.doe" }
@userId = 5cd6831f1acb4f0b691c4ef6

### Get current user's profile
GET  http://localhost:5000/api/profile/me
x-auth-token: {{token}}

### Create or update user's profile
POST  http://localhost:5000/api/profile
x-auth-token: {{token}}
content-type: application/json

{{profile}}

### Get all profiles
GET  http://localhost:5000/api/profile

### Get profile by userId
GET  http://localhost:5000/api/profile/user/{{userId}}

### Delete profile and user
DELETE  http://localhost:5000/api/profile
x-auth-token: {{token}}